// Generated by HybirdPB CodeGenerator(1.2.0). DO NOT EDIT!
// Generation date is 2020-06-14 14:29:32

package com.vdd.v1.user;

import com.alipay.mobile.framework.service.ext.annotation.CheckLogin;
import com.alipay.mobile.framework.service.annotation.OperationType;
import com.alipay.mobile.framework.service.annotation.SignCheck;

import com.vdd.v1.user.model.User;
import com.vdd.v1.user.request.UserQueryGetReq;
import com.vdd.v1.user.request.UserAddPostReq;
   
public interface UserClient {

    @SignCheck
    @OperationType("com.vdd.v1.user.add") 
    public String userAddPost(UserAddPostReq requestParam);


    @SignCheck
    @OperationType("com.vdd.v1.user.query")
    public User userQueryGet (UserQueryGetReq requestParam);


    @SignCheck
    @OperationType("com.vdd.v1.user.login") 
    public String loginGet();


}