// Generated by HybirdPB CodeGenerator(1.2.0). DO NOT EDIT!
// Generation date is 2020-06-14 14:29:32

package com.vdd.v1.user.request;


public class UserQueryGetReq {
    public Long userId;

}