// Generated by HybirdPB CodeGenerator(1.2.0). DO NOT EDIT!
// Generation date is 2020-06-14 14:29:32

package com.vdd.v1.user.request;

import com.vdd.v1.user.model.User;

public class UserAddPostReq {
    public User _requestBody;

}